#!/bin/bash
#SBATCH --job-name=write_GLORI_index
#SBATCH --partition=FIXME
#SBATCH --mem=128G
#SBATCH -N 1         # max nodes
#SBATCH --time=1-0:00:00
#SBATCH --cpus-per-task=16
#SBATCH --output=slurm_log/%x-%j.log

# where to write files
# outdir="index/"
outdir="index_hg38/"
# where GLORI files are
GLORI_root="FIXME path to git/liucongcas/GLORI-tools/"
# number of threads to use (this uses a peak of ~88 GB for building genomic indices)
threads=16

# Writes index for GLORI-seq.
echo `date`: started

# Load modules
# FIXME these will probably need tweaking
module load trimgalore seqkit fastx-toolkit star bowtie samtools

# Load Python modules from a venv;
# the non-built-in modules were installed using:
# pip3 install bio pandas pysam statsmodels
source (FIXME path to venv, if you use this)

genome_fastafile="hg38.fa"

mkdir -p ${outdir}

cd ${outdir}

echo `date` downloading files
# download files
wget --timestamping https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109.20190905/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_assembly_report.txt
wget --timestamping https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109.20190905/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gtf.gz

echo `date` 1.2 download reference genome and transcriptome
# using downloaded file, as README notes that chromosome names
# need to start with "chr"
wget --timestamping https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
wget --timestamping https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109.20190905/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_rna.fna.gz

# uncompress (keeping original files, to prevent re-downloading)
gunzip --keep hg38.fa.gz
gunzip --keep GCF_000001405.39_GRCh38.p13_genomic.gtf.gz
gunzip --keep GCF_000001405.39_GRCh38.p13_rna.fna.gz

echo `date` write out unmodified genome index

# based on code in pipelines/build_genome_index.py
STAR --runMode genomeGenerate --runThreadN ${threads} \
--genomeDir hg38 --genomeFastaFiles hg38.fa \
--genomeSAindexNbases 14 --limitGenomeGenerateRAM 84807429045

echo `date` convert files
python ${GLORI_root}/get_anno/change_UCSCgtf.py -i GCF_000001405.39_GRCh38.p13_genomic.gtf -j GCF_000001405.39_GRCh38.p13_assembly_report.txt -o GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens

echo echo `date` 2.1

python ${GLORI_root}/pipelines/build_genome_index.py -p ${threads} -f ${genome_fastafile} -p ${threads} -pre hg38

echo echo `date` 2.2.1

python ${GLORI_root}/get_anno/gtf2anno.py -i GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens -o GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl

awk '$3!~/_/&&$3!="na"' GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl | sed '/unknown_transcript/d'  > GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl2

echo `date` Get the longest transcript:

python ${GLORI_root}/get_anno/selected_longest_transcrpts_fa.py -anno GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl2 -fafile GCF_000001405.39_GRCh38.p13_rna.fna --outname_prx GCF_000001405.39_GRCh38.p13_rna2.fa

echo `date` 2.2.2

python ${GLORI_root}/pipelines/build_transcriptome_index.py -p ${threads} -f GCF_000001405.39_GRCh38.p13_rna2.fa -pre GCF_000001405.39_GRCh38.p13_rna2.fa

# FIXME change output name of index?
ln -s hg38.rvsCom hg38.revCom

echo `date` 3.1 get annotation at single-base resolution

# jtb: omitting "-threads 20" arg to this
python ${GLORI_root}/get_anno/anno_to_base.py -i GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl2 -o GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl2.baseanno

echo `date` 3.2 get required annotation file for further removal of duplicated loci

# jtb: changing ".fa" => ".fna"
python ${GLORI_root}/get_anno/gtf2genelist.py -i GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens -f GCF_000001405.39_GRCh38.p13_rna.fna -o GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.genelist > output2

awk '$6!~/_/&&$6!="na"' GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.genelist > GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.genelist2

echo `date` 3.3 Removal of duplicated loci in the annotation file

python ${GLORI_root}/get_anno/anno_to_base_remove_redundance_v1.0.py -i GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl2.baseanno -o GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.tbl2.noredundance.base -g GCF_000001405.39_GRCh38.p13_genomic.gtf_change2Ens.genelist2

echo `date`: finished

